version: '3'
services:
  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    build: ../booking-be
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=booking
      - SERVER_ADDRESS=:8080
      - TOKEN_SECRET=my-ultra-secure-json-web-token-string
      - TOKEN_EXPIRED_IN=60m
      - TOKEN_MAXAGE=60
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

volumes:
  db_data:
